# Generated by Django 5.1.3 on 2024-11-22 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_machine_name_alter_machine_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name='ID',
            ),
        ),
        migrations.AlterField(
            model_name='machine',
            name='id',
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name='ID',
            ),
        ),
        migrations.AlterField(
            model_name='machine',
            name='status',
            field=models.CharField(
                choices=[
                    ('ACTVIE', 'Active'),
                    ('BOOKED', 'Booked'),
                    ('REINSTALLING', 'Reinstalling'),
                ],
                default='ACTVIE',
                max_length=50,
            ),
        ),
    ]
