# Generated by Django 5.1.3 on 2024-11-28 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_booking_booked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='bookedBy',
            new_name='booked_by',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='bookedFrom',
            new_name='booked_from',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='bookedUntil',
            new_name='booked_until',
        ),
        migrations.RenameField(
            model_name='machine',
            old_name='cpuCores',
            new_name='cpu_cores',
        ),
        migrations.RenameField(
            model_name='machine',
            old_name='operatingSystem',
            new_name='operating_system',
        ),
    ]
