# Generated by Django 5.1.3 on 2024-11-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='status',
            field=models.CharField(
                choices=[
                    ('ACTVIE', 'Active'),
                    ('BOOKED', 'BOOKED'),
                    ('REINSTALLING', 'Reinstalling'),
                ],
                default='ACTVIE',
                max_length=50,
            ),
        ),
    ]
